# For docs see https://pre-commit.com
---
default_language_version:
  python: python3.8

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: pipenv run isort --check --diff
        language: python
        types: [python]
        exclude: ^tests/
      - id: pylint
        name: pylint
        entry: pipenv run pylint
        language: python
        types: [python]
        exclude: ^tests/
      - id: black
        name: black
        entry: pipenv run black --check
        language: python
        types: [python]