version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nlb-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gbc19pz13htz"
s3_prefix = "nlb-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
