AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NoLuvBeats API
  Serverless API for NoLuvBeats

###############################################################################
### Globals
###############################################################################

Globals:
  Function:
    Timeout: 300
    Runtime: python3.8
    Environment:
      Variables:
        ASSET_BUCKET: &asset_bucket nlb-site-assets
        KIT_TABLE: &kit_table nlb-kit

###############################################################################
### Resources
###############################################################################

Resources:
  NoLuvBeatsAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: api

  KitInitiateUploadFunction:
    Type: 'AWS::Serverless::Function' # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/kit/initiate_upload
      Handler: app.handler
      Description: >-
        A Function that generates a presigned url to be used in
        the frontend to upload kits to nlb-site-assets.
      Layers:
        - !Ref SharedLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: AssetBucketPut
              Effect: Allow
              Action:
                - 's3:PutObject'
              Resource:
                - !Sub
                  - 'arn:aws:s3:::${bucketName}/*'
                  - { bucketName: *asset_bucket }
      Events:
        KitInitiateUpload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NoLuvBeatsAPI
            Path: '/kit/initiate-upload'
            Method: POST

  KitPutFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: functions/kit/put
      Handler: app.handler
      Description: >-
        A Function that retrieves kit data for the object that has
        been updated in nlb-site-assets and puts to dynamodb.
      Layers:
        - !Ref SharedLayer
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: AssetBucketGet
              Effect: Allow
              Action:
                - 's3:GetObject'
              Resource:
                - !Sub
                  - 'arn:aws:s3:::${bucketName}/*'
                  - { bucketName: *asset_bucket }
            - Sid: KitTablePut
              Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${KitTable}'
      Events:
        NlbSiteAssetsEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: AssetBucket
            Events:
              - 's3:ObjectCreated:*'

  SharedLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: nlb-shared-layer
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

  KitTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: *kit_table
      PrimaryKey:
        Name: file_name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: *asset_bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

###############################################################################
### Outputs
###############################################################################

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NoLuvBeatsAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${NoLuvBeatsAPI}.execute-api.${AWS::Region}.amazonaws.com/api/kit/initiate-upload"
  KitInitiateUploadFunction:
    Description: "Kit Initiate Upload Lambda Function ARN"
    Value: !GetAtt KitInitiateUploadFunction.Arn
  KitInitiateUploadFunctionIamRole:
    Description: "Implicit IAM Role created for KitInitiateUploadFunction"
    Value: !GetAtt KitInitiateUploadFunctionRole.Arn
  KitPutFunction:
    Description: "Kit Put lambda Function ARN"
    Value: !GetAtt KitPutFunction.Arn
  KitPutFunctionIamRole:
    Description: "Implicit IAM Role created for KitPutFunction"
    Value: !GetAtt KitPutFunctionRole.Arn
  KitTable:
    Description: "Kit dynamodb table ARN"
    Value: !GetAtt KitTable.Arn
  AssetBucket:
    Description: "Asset bucket ARN"
    Value: !GetAtt AssetBucket.Arn
