AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NoLuvBeats API
  Serverless API for NoLuvBeats

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Runtime: python3.8
    Environment:
      Variables:
        ASSET_BUCKET: nlb-site-assets
        ASSET_DB_TABLE: nlb-db-asset-metadata


Resources:
  NoLuvBeatsAPI:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: Prod

  AssetInitiateUploadFunction:
    Type: 'AWS::Serverless::Function' # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/asset/initiate_upload
      Handler: app.handler
      Description: >-
        A Function that generates a presigned url to be used in
        the frontend to upload assets to nlb-site-assets.
      Layers:
        - !Ref SharedLayer
      Events:
        AssetInitiateUpload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NoLuvBeatsAPI
            Path: '/api/initiate-upload'
            Method: POST

  AssetMetadataPostFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: functions/asset/metadata_post
      Handler: app.handler
      Description: >-
        A Function that retrieves metadata for the object that has
        been updated in nlb-site-assets.
      Events:
        NlbSiteAssetsEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: NlbAssetBucket
            Events:
              - 's3:ObjectCreated:*'

  SharedLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: nlb-api-shared-layer
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

  NlbAssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nlb-site-assets

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NoLuvBeatsAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${NoLuvBeatsAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/initiate-upload"
  AssetInitiateUploadFunction:
    Description: "Asset Initiate Upload Lambda Function ARN"
    Value: !GetAtt AssetInitiateUploadFunction.Arn
  AssetInitiateUploadFunctionIamRole:
    Description: "Implicit IAM Role created for AssetInitiateUploadFunction"
    Value: !GetAtt AssetInitiateUploadFunctionRole.Arn
