AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nlb-api

  Serverless API for NLB

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    BinaryMediaTypes:
      - application~1zip
  Function:
    Timeout: 300
    Runtime: python3.8
    Environment:
      Variables:
        ASSET_BUCKET: nlb-site-assets

Resources:
  InitiateUploadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/initiate_upload
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Events:
        BeatUpload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/initiate-upload
            Method: post
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NlbApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BeatUploadFunction:
    Description: "Initiate Upload Lambda Function ARN"
    Value: !GetAtt InitiateUploadFunction.Arn
  BeatUploadFunctionIamRole:
    Description: "Implicit IAM Role created for InitiateUploadFunction"
    Value: !GetAtt InitiateUploadFunctionRole.Arn
