AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NoLuvBeats API

  Serverless API for NoLuvBeats

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Runtime: python3.8
    Environment:
      Variables:
        ASSET_BUCKET: nlb-site-assets


Resources:
  NoLuvBeatsAPI:
    Type: 'AWS::Serverless:Api'
    Properties:
      StageName: Prod

  ExampleFunction:
    Type: 'AWS::Serverless::Function' # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/example
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Events:
        ExampleAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NoLuvBeatsAPI
            Path: '/api/example'
            Method: GET

  AssetInitiateUploadFunction:
    Type: 'AWS::Serverless::Function' # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/asset/initiate_upload
      Handler: app.handler
      Layers:
        - !Ref SharedLayer
      Events:
        InitiateUploadAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref NoLuvBeatsAPI
            Path: '/api/initiate-upload'
            Method: POST

  SharedLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: nlb-api-shared-layer
      ContentUri: layers/shared
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NoLuvBeatsAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/asset-initiate-upload"
  BeatUploadFunction:
    Description: "Asset Initiate Upload Lambda Function ARN"
    Value: !GetAtt AssetInitiateUploadFunction.Arn
  BeatUploadFunctionIamRole:
    Description: "Implicit IAM Role created for AssetInitiateUploadFunction"
    Value: !GetAtt AssetInitiateUploadFunctionRole.Arn
