AWSTemplateFormatVersion: '2010-09-09'
Description: >
  NoLuvBeats Serverless API

###############################################################################
### Resources
###############################################################################

Resources:
  AssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nlb-site-assets
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
            AllowedOrigins:
              - 'http://localhost:3000'
              - 'https://noluvbeats.com'
            MaxAge: 1800
            Id: AssetBucketCorsConfiguration
  KitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: nlb-kits
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: file_name
          AttributeType: S
        - AttributeName: created_date
          AttributeType: S
      KeySchema:
        - AttributeName: file_name
          KeyType: HASH
        - AttributeName: created_date
          KeyType: RANGE

###############################################################################
### Outputs
###############################################################################

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  KitTable:
    Description: 'Kit dynamodb table ARN'
    Value: !GetAtt KitTable.Arn
  AssetBucket:
    Description: 'Asset bucket ARN'
    Value: !GetAtt AssetBucket.Arn
